canton {
  participants {
    participant1 {
      ledger-api { port = 6865 }
      http-ledger-api { port = 7575 }
      admin-api { port = 6866 }
      parameters.alpha-version-support = true
    }

    participant2 {
      ledger-api { port = 6965 }
      http-ledger-api { port = 7675 }
      admin-api { port = 6966 }
      parameters.alpha-version-support = true
    }

    participant3 {
      ledger-api { port = 7065 }
      http-ledger-api { port = 7775 }
      admin-api { port = 7066 }
      parameters.alpha-version-support = true
    }
  }

  sequencers {
    sequencer1 {
      public-api { port = 10018 }
      admin-api { port = 10019 }
      parameters.alpha-version-support = true
    }
  }

  mediators {
    mediator1 {
      admin-api { port = 10029 }
    }
  }

  parameters {
    non-standard-config = yes
    alpha-version-support = yes
  }

  monitoring.logging {
    event-details = true
    api {
      message-payloads = true
      max-message-lines = 10000
      max-string-length = 10000
      max-metadata-size = 10000
      max-method-length = 1000
    }
  }
}

