canton.participants.sandbox.parameters.alpha-version-support = true
canton.sequencers.sequencer1.parameters.alpha-version-support = true

canton.parameters {
    non-standard-config = yes
    alpha-version-support = yes
}

# From Judy's presentation: enable deep protocol-level logging
# (shows confirmation requests, views, envelopes, and message payloads)
canton.monitoring.logging {
  event-details = true
  api {
    message-payloads = true
    max-message-lines = 10000
    max-string-length = 10000
    max-metadata-size = 10000
    max-method-length = 1000
  }
}