canton {
  parameters {
    non-standard-config = yes
    alpha-version-support = yes
  }

  participants.sandbox {
    admin-api.port = 5018
    ledger-api.port = 6865
    parameters.alpha-version-support = true
  }

  sequencers.sequencer1 {
    admin-api.port = 5020
    public-api.port = 5021
    parameters.alpha-version-support = true
  }

  mediators.mediator1 {
    admin-api.port = 5022
  }
}

