# Script assumes that (unformatted) html doc has been generated in the docs/ directory, and has not been comitted to git.

# The following will force exit if any command on a line fails. This is to avoid accidently comitting if things go wrong
set -o errexit

HEAD=$(git rev-parse --short HEAD)

export GIT_AUTHOR_NAME="Luciano Joublanc"
export GIT_AUTHOR_EMAIL="luciano.joublanc@digitalasset.com"
export GIT_COMMITTER_NAME=${GIT_AUTHOR_NAME}
export GIT_COMMITTER_EMAIL=${GIT_AUTHOR_EMAIL}

git switch github-pages
rm docs/*.html
mv -v .docs/*.html docs
# This is a bit weird as we're using the same input/output. This takes the damlc generated HTML and adds headers/styling to it.
for f in docs/*.html
  do pandoc -s --template docs/da-style/da-pandoc.html --metadata pagetitle="Contingent Claims" -o $f $f
done
git add docs
git commit -m "Autogenerated doc for $HEAD" || echo "Docs have not changed" # In case docs haven't changed

# The environment varibale is set in the CI
git push https://${GITHUB_TOKEN}@github.com/digital-asset/contingent-claims.git
